version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:5.0
    container_name: ecolearn-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ecolearn123
      MONGO_INITDB_DATABASE: ecolearn
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecolearn-network

  # Backend API
  backend:
    build: ./backend
    container_name: ecolearn-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:ecolearn123@mongodb:27017/ecolearn?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRE: 7d
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: your-email@gmail.com
      EMAIL_PASS: your-app-password
      RECAPTCHA_SECRET_KEY: your-custom-recaptcha-secret-key
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - ecolearn-network

  # Frontend React App
  frontend:
    build: ./frontend
    container_name: ecolearn-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - ecolearn-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: ecolearn-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - ecolearn-network

volumes:
  mongodb_data:

networks:
  ecolearn-network:
    driver: bridge